services:
  - type: web
    name: diabetic-retinopathy-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: diabetic-retinopathy-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379/0
databases:
  - name: diabetic-retinopathy-db
    databaseName: diabetic_retinopathy
    user: your-db-username
    password: your-db-password
    plan: free

